version: '3.8'

services:
  aipolish-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aipolish_server
    restart: always
    extra_hosts:                               
      - "api.devdove.cc:108.162.198.183"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - mysql
      - redis  # 让 App 启动前先等待 Redis 启动

  mysql:
    image: m.daocloud.io/docker.io/library/mysql:8.0
    container_name: aipolish_mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Shanghai
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./backend/model/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 将 Redis 纳入集群编排
  redis:
    image: redis:7.0-alpine  # 使用 alpine 轻量级镜像
    container_name: aipolish_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data  # 将 Redis 数据持久化到宿主机
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # 挂载配置文件
    # 使用配置文件启动，限制内存并开启持久化
    command: redis-server /usr/local/etc/redis/redis.conf

# 声明数据卷
volumes:
  mysql_data:
  redis_data:  # 🟢 声明 Redis 数据卷
